version: '3'

services:
  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
